"""
Django settings for {{cookiecutter.project_name}} project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from {{cookiecutter.project_name}}.settings import *  # noqa: F401, F403
from {{cookiecutter.project_name}}.settings import BASE_DIR
from {{cookiecutter.project_name}}.settings import ENV
from {{cookiecutter.project_name}}.settings import INSTALLED_APPS
from {{cookiecutter.project_name}}.settings import MIDDLEWARE


ROOT_URLCONF = "{{cookiecutter.project_name}}.urls_admin"

if "development" in ENV:
    ENV_COLOR = "grey"
if "staging" in ENV:
    ENV_COLOR = "green"
if "next" in ENV:
    ENV_COLOR = "orange"
if "prod" in ENV:
    ENV_COLOR = "red"

# Application definition
INSTALLED_APPS += [
    "django.contrib.admin",
    "django.contrib.messages",
    "django.contrib.admindocs",
]

MIDDLEWARE += [
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR + "/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "{{cookiecutter.project_name}}.context_processors.from_settings",
            ]
        },
    }
]
