docker-sign-in: &docker-sign-in
  name: login to doker remote
  command: |
    docker login \
      --username $DOCKER_USER \
      --password $DOCKER_PASS \
      https://docker-registry.bimdata.io

compile-minify: &compile-minify
  name: run compile/minify
  command: |
    python3.8 -m pip install compile-minifier
    compileminify run

mapping-var-env: &mapping-var-env
  name: define var with branch
  command: |
    case "$CIRCLE_BRANCH" in
      "master") ENV=prod
        ;;
      "release") ENV=next
        ;;
      "develop") ENV=staging
        ;;
    esac
    echo 'export ENV='$ENV >> $BASH_ENV

version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  test:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_PASSWORD: "{{cookiecutter.project_name}}"
          POSTGRES_DB: "{{cookiecutter.project_name}}"
          POSTGRES_USER: "{{cookiecutter.project_name}}"
      - image: rabbitmq:3.6-management-alpine
        environment:
          RABBITMQ_DEFAULT_USER: {{cookiecutter.project_name}}
          RABBITMQ_DEFAULT_PASS: {{cookiecutter.project_name}}
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ "{{" }} checksum "poetry.lock" {{ "}}" }}
      - run:
          name: install dependencies
          command: poetry install
      - run:
          name: run migrations test
          command: poetry run python manage.py migrate
      - run:
          name: run test
          command: poetry run python manage.py test

  build_and_push:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: *mapping-var-env
      - run: *docker-sign-in
      - run: *compile-minify
      - run:
          name: backup previous image
          command: |
            if export DOCKER_CLI_EXPERIMENTAL=enabled && docker manifest inspect "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:$ENV" > /dev/null; then
              docker pull "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:$ENV"
              docker image tag "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:$ENV" "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:prev-$ENV"
              docker push "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:prev-$ENV"
            fi
      - run:
          name: build docker image
          command: |
            echo $CIRCLE_SHA1 > VERSION
            docker build --tag "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:$ENV" .
      - run:
          name: push new image
          command: docker push "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:$ENV"
      - run:
          name: push latest tag image
          command: |
            if [[ "$CIRCLE_BRANCH" == "develop" ]]; then
              docker tag "docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:$ENV" docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:latest
              docker push docker-registry.bimdata.io/bimdata/{{cookiecutter.project_name}}:latest
            fi

  deploy:
    <<: *container_config
    steps:
      - setup_remote_docker
      - run: *docker-sign-in
      - run: *mapping-var-env
      - run:
          name: ansible deployment
          command: |
            docker run -e ANSIBLE_VAULT_PASSWD docker-registry.bimdata.io/bimdata/deployment:latest \
              ansible-playbook \
              --inventory-file inventories/$ENV \
              --tags {{cookiecutter.project_name}} \
              --extra-vars "ansible_ssh_private_key_file=./files/deploy_rsa" \
              --user deploy  \
              deploy.yml

workflows:
  test_and_deploy:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - release
                - develop
      - deploy:
          requires:
            - build_and_push
