repos:
-   repo: https://github.com/psf/black
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    hooks:
    -   id: reorder-python-imports
-   repo: https://gitlab.com/pycqa/flake8
    hooks:
    - id: flake8
      args: ["--config=setup.cfg"]
-   repo: local
    hooks:
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: bash -c "./manage.py makemigrations --check --dry-run"
      types: ["python"]
      pass_filenames: false
